axi_ENV_PKG		?= \
	+incdir+$(PROJ_VIP_HOME)/environment_packages/axi_env \
	$(PROJ_VIP_HOME)/environment_packages/axi_env/axi_env_pkg.sv

# can declare other filelist like HDL, or XRTL
comp_env_pkg:
	$(COMP_HDL) $(axi_ENV_PKG)