axi_PKG		?= \
	+incdir+$(PROJ_VIP_HOME)/interface_packages/axi_if \
	-F $(PROJ_VIP_HOME)/interface_packages/axi_if/axi_pkg_filelist.f

# can declare other filelist like HDL, or XRTL
comp_axi_pkg:
	$(COMP_HDL) $(axi_PKG)