add wave -noupdate /hdl_top/hdl_if/clk
add wave -noupdate /hdl_top/hdl_if/rstn
add wave -noupdate /hdl_top/hdl_if/awvalid
add wave -noupdate /hdl_top/hdl_if/awready
add wave -noupdate /hdl_top/hdl_if/awid
add wave -noupdate /hdl_top/hdl_if/awlen
add wave -noupdate /hdl_top/hdl_if/awsize
add wave -noupdate /hdl_top/hdl_if/awaddr
add wave -noupdate /hdl_top/hdl_if/awburst
add wave -noupdate /hdl_top/hdl_if/wvaild
add wave -noupdate /hdl_top/hdl_if/wready
add wave -noupdate /hdl_top/hdl_if/wid
add wave -noupdate /hdl_top/hdl_if/wdata
add wave -noupdate /hdl_top/hdl_if/wstrb
add wave -noupdate /hdl_top/hdl_if/wlast
add wave -noupdate /hdl_top/hdl_if/bready
add wave -noupdate /hdl_top/hdl_if/bvalid
add wave -noupdate /hdl_top/hdl_if/bid
add wave -noupdate /hdl_top/hdl_if/bresp
add wave -noupdate /hdl_top/hdl_if/arready
add wave -noupdate /hdl_top/hdl_if/arid
add wave -noupdate /hdl_top/hdl_if/araddr
add wave -noupdate /hdl_top/hdl_if/arlen
add wave -noupdate /hdl_top/hdl_if/arsize
add wave -noupdate /hdl_top/hdl_if/arburst
add wave -noupdate /hdl_top/hdl_if/arvalid
add wave -noupdate /hdl_top/hdl_if/rid
add wave -noupdate /hdl_top/hdl_if/rdata
add wave -noupdate /hdl_top/hdl_if/rstrb
add wave -noupdate /hdl_top/hdl_if/rresp
add wave -noupdate /hdl_top/hdl_if/rlast
add wave -noupdate /hdl_top/hdl_if/rready