$PROJ_PB_HOME/axi_mem/rtl/axi_mem.sv
$PROJ_VIP_HOME/interface_packages/axi_if/axi_pkg_hdl.sv
$PROJ_VIP_HOME/interface_packages/axi_if/axi_if_pkg.sv
$PROJ_VIP_HOME/interface_packages/axi_if/src/axi_if.sv
$PROJ_VIP_HOME/interface_packages/axi_if/src/axi_driver_bfm.sv
$PROJ_VIP_HOME/interface_packages/axi_if/src/axi_monitor_bfm.sv
$PROJ_VIP_HOME/environment_packages/axi_env/axi_env_pkg.sv
$PROJ_PB_HOME/axi_mem/tb/sequences/axi_sequences_pkg.sv
$PROJ_PB_HOME/axi_mem/tb/tests/tests_pkg.sv
$PROJ_PB_HOME/axi_mem/tb/testbenches/hdl_top.sv
$PROJ_PB_HOME/axi_mem/tb/testbenches/hvl_top.sv
